name: Ryan Thomson | Web Design and Development

markdown: kramdown

permalink: /blog/:year/:month/:day/:title

url: "https://ryanthomsonweb.co.uk" # the base hostname and protocol for your site

plugins:
  - jekyll-sitemap
  - jekyll-paginate

paginate: 5

paginate_path: "/blog/page:num/"
