name: Hank Quinlan, Horrible Cop

markdown: kramdown

permalink: /blog/:year/:month/:day/:title

url: "https://ryanthomsonweb.github.io" # the base hostname and protocol for your site

plugins:
  - jekyll-sitemap
  - jekyll-paginate

paginate: 5

paginate_path: "/blog/page:num/"
